### ISSUE TITLE
"We removed tokens and classes" section is unclear

### ISSUE THREAD

**Issue by Burgestrand** [phlex-ruby/phlex.fun#37]
Looking to try out the v2 alpha, but it turns out I'm using `tokens` (not extensively) so I got confused by the section about them!

I know this is under development, so I might be opening this issue far too soon.

---

https://github.com/phlex-ruby/phlex.fun/blob/96544972e066c2a62ea67909b64c6c1e5ef49a3f/guides/v2-upgrade.md?plain=1#L17-L21

It refers to "here", but it doesn't seem to be an actual link. It's unclear where "here" is.

Additionally, "new standard capabilities of attributes". What are those?

---

![PixelSnap 2024-09-06 at 15 23 23@2x](https://github.com/user-attachments/assets/f86df0be-a007-4afc-a548-729ebb32880e)

**Comment by joeldrapper** [comment]
Ops, “here” is a placeholder for me to remember to dig up the reference from git!

**Comment by joeldrapper** [comment]
Fixed https://beta.phlex.fun/guides/v2-upgrade#we-removed-tokens-and-classes
